spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/perfume
    username: root
    password: 1005
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
